### ISSUE TITLE
Feature suggestion(s)

### ISSUE THREAD

**Issue by jmiln** [briangwaltney/paren-hint.nvim#1]
I'm not sure how to add the setup bit with config options like other plugins have, or how easy it would be, but if you add that in at some point, I've got a couple suggestions for options.

- Show the opening bracket / paren in the virtual text
  - Just a toggle for the -1 here I think? https://github.com/briangwaltney/paren-hint.nvim/blob/e835ae43739eefc61481543d657b3350940d439a/lua/paren-hint/init.lua#L67
- Have a line comment at the beginning of the virtual text (Something the biscuits plugin did that I liked)
  - Example for js: `} catch (err) {  // try {`

**Comment by jmiln** [comment]
Quick update to this, I've poked around a bit, and if those are something you'd be interested in, I got the first of those working, and can PR it

**Comment by briangwaltney** [comment]
That should be pretty easy to add. I'll build it out really quick.

**Comment by briangwaltney** [comment]
Added in: https://github.com/briangwaltney/paren-hint.nvim/commit/d10062768042c873d5846e8e661c03ba3d4bca12

Default is to include the opening paren.
