### ISSUE TITLE
Treesitter check is possibly pointless

### ISSUE THREAD

**Issue by Gelio** [briangwaltney/paren-hint.nvim#2]
Hey, thanks for putting this plugin together! It looks quite useful!

I had trouble getting it to run. I noticed there is a `is_treesitter_active` function that is required to pass

https://github.com/briangwaltney/paren-hint.nvim/blob/3795067a2d5895f90c1f514c2a019f0836f4ce09/lua/paren-hint/init.lua#L9-L17

The variable names suggest that it is supposed to check if there is a parser for the current file type. I see some problems with it:

1. `nvim-treesitter.parser.get_parser_configs()` returns the configuration of all parsers, not just installed ones.
2. Parser names do not always match filetypes (e.g. the filetype for TSX is `typescriptreact`, but the parser name is [`tsx`](https://github.com/nvim-treesitter/nvim-treesitter/blob/22c5a0d833ac70e07a7a70ba4e29081a1072422b/lua/nvim-treesitter/parsers.lua#L2054-L2063)

I believe the correct implementation would be something like:

```lua
local function is_treesitter_active()
  local err, parser = pcall(function() return vim.treesitter.get_parser(0, vim.bo.filetype) end)
  return err == nil and parser ~= nil
end
```

This also does not involve `nvim-treesitter`, which means that dependency is no longer needed.

However, I don't see treesitter used in the plugin implementation. It just seems to iterate over the text. I'm not sure such a check is necessary at all. I suggest removing it, since right now, it prevents me from using the plugin with TypeScript or JavaScript, and I'm sure other users will be discouraged to use it as well.

I am not drafting any PRs because I'm not sure whether you plan on starting to using Treesitter soon (which suggests this check should be fixed, rather than removed).

**Comment by briangwaltney** [comment]
I noticed it wasn't needed either, but I added in there to disable the plugin on buffers that aren't code. Without the check, things like file trees and telescope have all sorts of issues.

I tried switching it with your function, and it didn't work at all afterward. I'll see if there is a better way to determine the treesitter activity.

I am seeing the issue with the tsx files as well though. 

Let me see what I can do.

**Comment by Gelio** [comment]
My bad, I didn't check the code before posting it. That was supposed to just give an idea how that could work.

Looks like the parameters of `vim.treesitter.get_parser` weren't necessary, they default to the current buffer. This implementation is working for me.

```lua
local function is_treesitter_active()
	local success, parser = pcall(function()
		return vim.treesitter.get_parser()
	end)
	return success and parser ~= nil
end
```

> I noticed it wasn't needed either, but I added in there to disable the plugin on buffers that aren't code. Without the check, things like file trees and telescope have all sorts of issues.

In this case, perhaps checking if `vim.bo.buftype == ""` is a better idea, as well as adding a disable-list based on filetypes? This is what I see indent-blankline is doing ([source](https://github.com/lukas-reineke/indent-blankline.nvim/blob/821a7acd88587d966f7e464b0b3031dfe7f5680c/lua/ibl/config.lua#L66-L84)), among other plugins.

**Comment by briangwaltney** [comment]
Fixed in https://github.com/briangwaltney/paren-hint.nvim/commit/ff3c85d244ef289983f051a5b3e5042fc91f4035

Thanks! That works better. I was going down the file type path as well, but I like this solution better for now. If the file types continue to be an issue for people, I'll work on a more robust solution.

Thanks for the help!

**Comment by briangwaltney** [comment]
Added the excluded file types solution after all. The treesitter solution was failing on `.json` files for me. Thanks for the indent-blankline solution.

**Comment by Gelio** [comment]
Sure thing, glad I could help 👍
